print('=========================')
print('\tLayang-Layang')
print('=========================')

dl1 = int(input('masukan nilai diagonal 1\t:'))
dl2 = int(input('masukan nilai diagonal 2\t:'))

luas = dl1 * dl2

# keliling = 2 * 22/7 * jr2
print('luas\t\t:',luas,'cm2')

# tanya = str(input('apakah ingin mencari keliling [y/t] : '))
# if tanya == 'y' :
#     print('kelilingt\t\t:',keliling,'cm2')
print('\tTERIMA KASIH')
# elif tanya == 't' :
#     print('OK terima Kasih')